# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"

cache:
  paths:
    - .m2/repository

# Étape 1 : Compilation du projet
build:
  stage: build
  image: maven:3.9.8-amazoncorretto-21
  script:
    - echo "Compilation du projet..."
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

# Étape 2 : Exécution des tests
test:
  stage: test
  image: maven:3.9.8-amazoncorretto-21
  script:
    - echo "Exécution des tests unitaires..."
    - mvn test
  allow_failure: false
  artifacts:
    when: always
    paths:
      - target/site/jacoco
    expire_in: 1 week

# Étape 3 : Génération et déploiement de la documentation API
pages:
  stage: deploy
  image: maven:3.9.8-amazoncorretto-21
  script:
    - "mvn clean package -Dcheckstyle.skip=true -DskipTests -B"
    - "mv target/apidocs public"
  artifacts:
    paths:
      - public
  
