stages:
  - build
  - test
  - verify
  - deploy

cache:
  paths:
    - .m2/repository

# Étape 1 : Compilation du projet
build:
  stage: build
  image: maven:3.9.8-amazoncorretto-21
  script:
    - echo "Compilation du projet..."
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

# Étape 2 : Exécution des tests unitaires
test:
  stage: test
  image: maven:3.9.8-amazoncorretto-21
  script:
    - echo "Exécution des tests unitaires..."
    - mvn test
  allow_failure: false
  artifacts:
    when: always
    paths:
      - target/site/jacoco
    expire_in: 1 week

# Étape 3 : Exécution des tests d'intégration
verify:
  stage: verify
  image: maven:3.9.8-amazoncorretto-21
  script:
    - echo "Exécution des tests d'intégration..."
    - mvn verify
  allow_failure: false
  artifacts:
    when: always
    paths:
      - target/site/jacoco
    expire_in: 1 week

# Étape 4 : Génération et déploiement de la documentation API
pages:
  stage: deploy
  image: maven:3.9.8-amazoncorretto-21
  script:
    - echo "Génération de la documentation Javadoc..."
    - mvn javadoc:javadoc
    - mkdir -p public
    - cp -r target/site/apidocs/* public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
